#!/bin/bash

# Use the meta-data service to get access tokens for the role associated
# to this machine

role=$1

tokens=$(curl -s --noproxy "*" http://169.254.169.254/latest/meta-data/iam/security-credentials/$role)

secret=$(echo "$tokens" | sed -n 's!.*"SecretAccessKey" : "\(.*\)".*!\1!p')
session=$(echo "$tokens" | sed -n 's!.*"Token" : "\(.*\)".*!\1!p')
access=$(echo "$tokens" | sed -n 's!.*"AccessKeyId" : "\(.*\)".*!\1!p')
expire=$(echo "$tokens" | sed -n 's!.*"Expiration" : "\(.*\)".*!\1!p')

if [ -z "$secret" -o -z "$session" -o -z "$access" ]
then
  echo "Unable to get assumed role credentials.  Could not find secret/access/session entries

$tokens" >&2
  exit 255
fi

echo export AWS_SESSION_TOKEN=$session
echo export AWS_SECRET_ACCESS_KEY=$secret
echo export AWS_ACCESS_KEY_ID=$access

echo Keys valid until $expire >&2
